# Generated by Django 3.1.3 on 2020-11-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201130_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Product creation time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', help_text='Product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, help_text='Product logo, rotated by 180 degrees on upload', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of the product', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='rotate_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of image rotation in seconds, ceiled', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(blank=True, help_text='Time of product update', null=True),
        ),
    ]
